--- #YAML:1.0
name:                Math-Counting
version:             0.0703
abstract:            Combinatorial counting operations
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Gene Boggs <gene@cpan.org>
